add_library(Effects effects/AmigaPalette.h effects/PaletteFader.cpp effects/PaletteFader.h effects/PaletteFlasher.cpp effects/PaletteFlasher.h effects/FotoSequence.cpp effects/FotoSequence.h effects/StorySequence.cpp effects/StorySequence.h effects/CodeCardCheck.cpp effects/CodeCardCheck.h effects/GameOptions.h effects/AmalMotion.cpp effects/AmalMotion.h effects/CreditScroll.cpp effects/CreditScroll.h effects/MenuSequence.cpp effects/MenuSequence.h effects/AttractSequence.cpp effects/AttractSequence.h effects/AmalAnim.cpp effects/AmalAnim.h effects/CharacterSelection.cpp effects/CharacterSelection.h)

add_library(Engine Engine.cpp Engine.h states/mirage/MirageState.cpp states/mirage/MirageState.h states/worldSoftware/WorldSoftwareState.cpp states/worldSoftware/WorldSoftwareState.h states/kneeAnimation/KneeAnimationState.cpp states/kneeAnimation/KneeAnimationState.h states/titleAndStory/TitleAndStoryState.cpp states/titleAndStory/TitleAndStoryState.h states/protectionCheck/ProtectionCheckState.cpp states/protectionCheck/ProtectionCheckState.h states/menu/MenuState.cpp states/menu/MenuState.h states/characterSelection/CharacterSelectionState.cpp states/characterSelection/CharacterSelectionState.h)
target_link_libraries(Engine PRIVATE VideoSystem AudioSystem ControllerSystem Effects)