add_library(States INTERFACE)

add_subdirectory(adverts)
add_subdirectory(characterSelection)
add_subdirectory(continueSelect)
add_subdirectory(ending)
add_subdirectory(gameOver)
add_subdirectory(highScore)
add_subdirectory(kneeAnimation)
add_subdirectory(level1)
add_subdirectory(level2)
add_subdirectory(level3)
add_subdirectory(menu)
add_subdirectory(mirage)
add_subdirectory(presents)
add_subdirectory(protectionCheck)
add_subdirectory(shared)
add_subdirectory(spiderLogo)
add_subdirectory(titleAndStory)
add_subdirectory(worldSoftware)
