add_subdirectory(abkToS3m)
add_subdirectory(amosCompact)
add_subdirectory(audioExtractor)
add_subdirectory(bitmapExtractor)
add_subdirectory(codeCards)
add_subdirectory(endingCredits)
add_subdirectory(fileContainer)
add_subdirectory(gameData)
add_subdirectory(headers)
add_subdirectory(jaguarCartridge)
add_subdirectory(levelScript)
add_subdirectory(packedArchive)
add_subdirectory(spriteSheet)
