set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR m68k)

set(JAGUAR_TOOLCHAIN_PREFIX "m68k-elf-" CACHE STRING "Prefix of the m68k-elf cross toolchain")

find_program(CMAKE_C_COMPILER ${JAGUAR_TOOLCHAIN_PREFIX}gcc REQUIRED)
find_program(CMAKE_CXX_COMPILER ${JAGUAR_TOOLCHAIN_PREFIX}g++ REQUIRED)
find_program(CMAKE_OBJCOPY ${JAGUAR_TOOLCHAIN_PREFIX}objcopy REQUIRED)
set(CMAKE_ASM_COMPILER ${CMAKE_C_COMPILER})

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(JAGUAR ON CACHE BOOL "Build for the Atari Jaguar" FORCE)

set(CMAKE_C_FLAGS_INIT "-m68000 -ffunction-sections -fdata-sections")
set(CMAKE_CXX_FLAGS_INIT "-m68000 -ffunction-sections -fdata-sections")
set(CMAKE_ASM_FLAGS_INIT "-m68000")
set(CMAKE_C_FLAGS_RELEASE_INIT "-O2 -fomit-frame-pointer")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O2 -fomit-frame-pointer")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-m68000 -nostartfiles -Wl,--gc-sections")
